# .github/workflows/deploy.yml

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/johnnythebot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH and check Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          if ! command -v docker &> /dev/null
          then
              echo "Docker could not be found, installing..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
              sudo systemctl start docker
              sudo systemctl enable docker
          fi
          sudo mkdir -p /root/JohnnyBot/logs

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/johnnythebot:latest
          sudo docker stop johnnythebot || true
          sudo docker rm johnnythebot || true
          sudo docker run -d --name johnnythebot --restart unless-stopped -v /root/JohnnyBot/logs:/app/logs \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e GUILD_ID=${{ secrets.GUILD_ID }} \
            ${{ secrets.DOCKER_USERNAME }}/johnnythebot:latest
          sudo docker ps -a
          sudo docker logs johnnythebot
